### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by Zatalyz** [schooner30/Renamer#1]
Hello,
Thank to update pyrenamer, best renamer I know. 
I am not expert dev and so... How to install Qtrenamer ? Maybe some information in the readme about "how to compile it" can be useful for noob like me :)

**Comment by Zatalyz** [comment]
So, need "qt-base" (in archlinux, probably same on other distribution). 

And in the folder, do :
```
qmake
make
./qtrenamer
```

I had this error first : 
`src/ui_mainwindow.h:13:10: erreur fatale: QtGui/QAction : Aucun fichier ou dossier de ce nom`

It is because QAction is under  QtWidgets/ now and not under QtGui/. I make a crap but it works : 
`sudo ln -s /usr/include/qt/QtWidgets/QAction /usr/include/qt/QtGui/QAction`

After that, "make" work good. And qtrenamer is launched !

**Comment by schooner30** [comment]
Well done for persevering.
The problem is that every version Qt seem to change header locations and grouping.
The code worked fine with whatever version I compiled it with at the time, but now they have 'rearranged the deckchairs',
**again**.
